faft: Close connections before reboot
To avoid the log message: "Remote Logging interrupted with following
error: rpc error: code = Unavailable desc = error reading from server:
EOF" close the ssh and grpc connections before rebooting instead of
after.

Also explicitly open the lid, instead of relying on power_state:reset
to clear the emulated lid state. That seems to avoid some problems
leaving the DUT off.

BUG=b:194908246
TEST=Ran test on dozens of leased duts

Change-Id: I9965420a5486d0088f4039583e79e1771d992bc2
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/tast-tests/+/4114800
Reviewed-by: Kshitij Shah <tij@google.com>
Commit-Queue: Jeremy Bettis <jbettis@chromium.org>
Tested-by: Jeremy Bettis <jbettis@chromium.org>
Auto-Submit: Jeremy Bettis <jbettis@chromium.org>