Revert "cujrecorder: Add CollectCLCP to collect cLCP value"
This reverts commit 0db07bda536a65342494b70b6e636c23307d7d41.

Reason for revert: Fails to build:

```
src/chromiumos/tast/local/ui/cujrecorder/recorder.go:974:19: undefined: pv
 * ERROR: chromeos-base/tast-remote-tests-cros-0.0.2-r14276::chromiumos failed (compile phase):
```

Original change's description:
> cujrecorder: Add CollectCLCP to collect cLCP value
>
> TPS.Browser.cLCP = (average of LCP2 - average of NavigationStartToFirstResponseStart)
>
> BUG=b:261745575, b:263777272
> TEST=fast_build.sh -T
>
> Change-Id: I16a34df3d42cc666ad1906f0ac45abe451ad79f5
> Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/tast-tests/+/4127556
> Commit-Queue: Alston Huang <alston.huang@cienet.com>
> Reviewed-by: Jun Sheng <shengjun@chromium.org>
> Tested-by: Alston Huang <alston.huang@cienet.com>

Bug: b:261745575, b:263777272
Change-Id: Ibfc3659c3c44124ccf3660fa2ccfad2ed8649745
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/tast-tests/+/4129857
Tested-by: Edward Hill <ecgh@chromium.org>
Reviewed-by: Avery Musbach <amusbach@chromium.org>
Commit-Queue: Edward Hill <ecgh@chromium.org>