ti50: Recognize fatal console messages
Adapt common routines for reading from GSC serial console to always recognize certain messages, such as "Panic", as being fatal, and reporting an error if any such message is seen.

With this change, the dashboard will show messages such as:
`Ti50 revives after reboot: Kernel panicked at 'fatal exception', <redacted>:413:0`
instead of the current
`Ti50 revives after reboot: Context deadline exceeded`.

BUG=b:331623486
TEST=make tast TAST_EXPR=gscdevboard.GSCTPM.i2c

Change-Id: I604bbc80a9f15347fa7491dbf6ee56c7f2d555e2
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/tast-tests/+/5401421
Reviewed-by: Zubin Mithra <zsm@chromium.org>
Tast-Review: Zubin Mithra <zsm@chromium.org>
Reviewed-by: Edward Hill <ecgh@chromium.org>
Commit-Queue: Jes Klinke <jbk@chromium.org>
Tested-by: Jes Klinke <jbk@chromium.org>