Revert "video: Don't inline "ExtraData" files in PlatformDecoding"
Revert submission 5665489

Reason for revert: Broke build:

--- FAIL: TestChromeStackDecoderVerificationParams (0.20s)
    chrome_stack_decoder_verification_test.go:518: chrome_stack_decoder_verification.go: Params is stale; run the following command to update:
        TAST_GENERATE_UPDATE=1 ~/chromiumos/src/platform/tast/tools/go.sh test -count=1 go.chromium.org/tast-tests/cros/local/bundles/cros/video
FAIL


Reverted changes: /q/submissionid:5665489

Change-Id: I3d99744cb8b20972e7869b831d33940cb1582e21
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/tast-tests/+/5666148
Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Tested-by: Miguel Casas-Sanchez <mcasas@chromium.org>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Auto-Submit: Miguel Casas-Sanchez <mcasas@chromium.org>