Revert "video: Extract VP9 test vectors to a common place"
Revert submission 5665489

Reason for revert: Broke build:

--- FAIL: TestChromeStackDecoderVerificationParams (0.20s)
    chrome_stack_decoder_verification_test.go:518: chrome_stack_decoder_verification.go: Params is stale; run the following command to update:
        TAST_GENERATE_UPDATE=1 ~/chromiumos/src/platform/tast/tools/go.sh test -count=1 go.chromium.org/tast-tests/cros/local/bundles/cros/video
FAIL


Reverted changes: /q/submissionid:5665489

Change-Id: If49ed0954a72892201703c0751de964cd6d1e7c2
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/tast-tests/+/5666150
Tested-by: Miguel Casas-Sanchez <mcasas@chromium.org>
Auto-Submit: Miguel Casas-Sanchez <mcasas@chromium.org>
Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>